### PR TITLE
Refactor structure

### PR DESCRIPTION
**Pull request by jcalcaben**
Move all Jekyll files into a src folder to avoid including non-docs related files into the final build.

Wrapped the build and develop processes inside npm scripts to allow for additional build processes (e.g. compiling scss, minifying js, etc).

### CODE REVIEW

**Comment by dshevtsov** [comment]
@jcalcaben consider renaming the folder to `assets` to make it more self-descriptive. `src` can seem ambiguous.

**Comment by jcalcaben** [comment]
`src` is a pretty common standard. It's the source of the project itself, and it indicates that it is intended to be the target for the `--source` command line option when generating the HTML.

**Comment by belbiy** [comment]
@jcalcaben , why not move the `_config-production.yml` to `src` folder as well? is there any reason to leave it in the root folder?

**Comment by jcalcaben** [comment]
no, there's no real reason to leave it in the root folder.

I'll update and move it into `src`.

**Pull request merged**
